---

- name: Start test service 
  hosts: test-swarm-manager-2

  tasks:

    - name: Start the TRO Investing service on the test swarm cluster.
      community.docker.docker_swarm_service:
        name: tro_investing 
        image: jasmit/tro_investing:v26.1.0.0.1
        env:
          ENVIRONMENT: "test"
        debug: true
        mounts:
          - source=/mnt/nfs_storage/test/tro_investing/logs
            target=/opt/app/tro_investing/logs
            type=bind
          - source=/mnt/nfs_storage/test/tro_investing/reports
            target=/opt/app/tro_investing/reports
            type=bind
          - source=/mnt/nfs_storage/test/tro_investing/stage
            target=/opt/app/tro_investing/stage
            type=bind


#  Example:
#  ansible-playbook playbooks/start_test_service.yaml

...
